CREATE TABLE friends (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE days (id BIGSERIAL PRIMARY KEY, date DATE NOT NULL UNIQUE, bill_minor BIGINT NOT NULL CHECK (bill_minor >= 0), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by TEXT);
CREATE TABLE day_entries (day_id BIGINT NOT NULL REFERENCES days(id) ON DELETE CASCADE, friend_id BIGINT NOT NULL REFERENCES friends(id), status TEXT NOT NULL CHECK (status IN ('ORDERED_OUT','BROUGHT_HOME_FOOD','NO_LUNCH')), PRIMARY KEY (day_id, friend_id));
CREATE TABLE settings (id SMALLINT PRIMARY KEY CHECK (id = 1), pool_minor BIGINT NOT NULL DEFAULT 200000, currency TEXT NOT NULL DEFAULT '');
INSERT INTO settings(id, pool_minor, currency) VALUES (1, 200000, '');
